proStage_accueil:
    path: /accueil
    controller: App\Controller\ProStageController::index

proStage_ressource123:
    path: /ressource/123
    controller: App\Controller\ProStageController::afficherRessources
